apiVersion: v1
kind: Namespace
metadata:
  name: somenamespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "somerole"
  namespace: somenamespace
rules:
  - apiGroups:
      - ""
    resources:
      - ""
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: somenamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: somerole
subjects:
  - kind: ServiceAccount
    name: somesa
    namespace: somenamespace
---
apiVersion: v1
kind: Service
metadata:
  name: testing
  labels:
    app: kubdiag
spec:
  ports:
    - port: 8080
      name: protoactor
  selector:
    app: kubdiag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubdiag
  template:
    metadata:
      labels:
        app: kubdiag
        version: v1
    spec:
      serviceAccountName: somesa
      automountServiceAccountToken: false
      containers:
        - name: kubdiag
          image: rogeralsing/kubdiagg:v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: KUBERNETES_SERVICE_PORT_HTTPS
              value: "443"
            - name: KUBERNETES_SERVICE_HOST
              value: "https://myaksclust-myresourcegroup-0dee3a-b7406f6e.hcp.westeurope.azmk8s.io"
            - name: "MONGO"
              value: "mongodb://mongo"
            - name: PROTOPORT
              value: "8080"
            - name: PROTOHOST
              value: "0.0.0.0"
            - name: "PROTOHOSTPUBLIC"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
