apiVersion: v1
kind: Service
metadata:
  name: testing
  labels:
    app: kubdiag
spec:
  ports:
    - port: 8080
      name: protoactor
  selector:
    app: kubdiag
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diagapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubdiag
  template:
    metadata:
      labels:
        app: kubdiag
        version: v1
    spec:
      containers:
        - name: kubdiag
          image: rogeralsing/kubdiagg
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: "MONGO"
              value: "mongodb://mongo"
            - name: PROTOPORT
              value: "8080"
            - name: PROTOHOST
              value: "0.0.0.0"
            - name: "PROTOHOSTPUBLIC"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP            